### ISSUE TITLE
 Cyrillic search does not work

### ISSUE THREAD

**Issue by cazumbra** [gmfmi/searchinGhost#13] opened 2021-08-15 20:28 UTC
Hi. I am using a construction like this

```
var searchinGhost = new SearchinGhost({
key: '20b4ff74b5d64e43afa50b70f1',

indexOptions: {
split: /\s+/,
encode: function(str) {
var regexp_replacements = {
"a": /[àáâãäå]/g,
"e": /[èéêë]/g,
"i": /[ìíîï]/g,
"o": /[òóôõöő]/g,
"u": /[ùúûüű]/g,
"y": /[ýŷÿ]/g,
"n": /ñ/g,
"c": /[ç]/g,
"s": /ß/g,
" ": /[-/]/g,
"": /['!"#$%&\()*+,-./:;<=>?@[]^_{|}~]/g, " ": /\s+/g, } str = str.toLowerCase(); for (var key of Object.keys(regexp_replacements)) { str = str.replace(regexp_replacements[key], key); } return str === " " ? "" : str; } }, postsFields: ['title', 'url', 'excerpt'], postsExtraFields: ['tags'], outputChildsType: 'h3', indexedFields: ['title', 'string_tags', 'plaintext', 'url'], template: function(post) { return ${post.title}${post.published_at}${post.tags[0].name}`
},
customProcessing: function(post) {
if (post.tags) post.string_tags = post.tags.map(o => o.name).join(' ').toLowerCase();
return post;
},
emptyTemplate: function() {
return 'No result'
}
});
```

 Unfortunately, there are no articles written in Cyrillic. Also, for some reason, the date of writing the article is not

**Comment by gmfmi** [comment] 2021-08-16 15:10
Hi @cazumbra,

It looks like the issue is coming from the syntax. If you try to lint or validate your code, it is not javascript valid. I think SearchinGhost simply can not start because of that.

Could you try with this patched configuration?

```js
var searchinGhost = new SearchinGhost({
  key: '20b4ff74b5d64e43afa50b70f1',
  indexOptions: {
    split: /\s+/,
    encode: function (str) {
      var regexp_replacements = {
        "a": /[àáâãäå]/g,
        "e": /[èéêë]/g,
        "i": /[ìíîï]/g,
        "o": /[òóôõöő]/g,
        "u": /[ùúûüű]/g,
        "y": /[ýŷÿ]/g,
        "n": /ñ/g,
        "c": /[ç]/g,
        "s": /ß/g,
        " ": /[-/]/g,
        "": /['!"#$%&\\()\*+,-./:;<=>?@[\]^_`{|}~]/g,
        " ": /\s+/g,
      }
      str = str.toLowerCase();
      for (var key of Object.keys(regexp_replacements)) {
        str = str.replace(regexp_replacements[key], key);
      }
      return str === " " ? "" : str;
    }
  },
  postsFields: ['title', 'url', 'excerpt'],
  postsExtraFields: ['tags'],
  outputChildsType: 'h3',
  indexedFields: ['title', 'string_tags', 'plaintext', 'url'],
  template: function (post) {
    return `${post.title} ${post.published_at} ${post.tags[0].name}`
  },
  customProcessing: function (post) {
    if (post.tags) post.string_tags = post.tags.map(o => o.name).join(' ').toLowerCase();
    return post;
  },
  emptyTemplate: function () {
    return 'No result'
  }
});
```

**Comment by cazumbra** [comment] 2021-08-16 18:11
That doesn't work either

**Comment by gmfmi** [comment] 2021-08-16 18:16
Is your website/blog publicly accessible? If so, could you share the URL here?

I tested the configuration targeting the Ghost demo site and it works just fine. Something probably conflicts in your implementation.

**Comment by cazumbra** [comment] 2021-08-16 18:46
My site is hosted locally. Search works only with English letters, it does not work with Cyrillic letters

**Comment by gmfmi** [comment] 2021-08-16 19:07
Well, I do not know how to help you out on this one. As an example, some SearchinGhost users setup search on blog containing both english and japanese articles using the same configuration and it just works. I tested the multi-lang support with cyrillic, arabic and indian-like languages and I have never faced a similar issue.

Hope you will find a way to achieve what you are looking for.  Feel free to add new comments if you get new inputs. For now, I am closing this issue.

**Closed as completed by gmfmi** 2021-08-16 19:07 UTC
