### ISSUE TITLE
Importing into TypeScript

### ISSUE THREAD

**Issue by marozzocom** [gmfmi/searchinGhost#1] opened 2020-05-26 06:01 UTC
Has anyone had any success importing SearchinGhost to a ghost theme project written in TypeScript? I could not get it to work with either

import SearchinGhost from 'searchinghost';

const SearchinGhost = require('searchinghost');

Also tried various other ways but I always end up getting an error from webpack that module is not a constructor, and basically always just receive an empty object.

I can use this by loading the file from unpkg, but I would've preferred bundling it. Importing the source file from node_modules does work, so it has to do with something about how the project is built and how TS imports modules. Unfortunately this sometimes gets a bit complicated.

**Comment by gmfmi** [comment] 2020-05-26 17:13
Hi @marozzocom, I never tried with TypeScript so I have no idea for that particuliar use case. I did not retry to use the library from NPM since I updated the build process to use Webpack.

Normally, based on the `package.json` configuration, NPM imports the `src/searchinghost.js` script so there is no bundling process involved. I will give a try with a classic JS project to be sure everything is fine. If you find any advice/literature on a way to make the library works with TypeScript, please let me know.

**Comment by gmfmi** [comment] 2020-05-26 21:04
Good news, the issue is not related to TypeScript! I tried to package a new project using parceljs and I got the same message. The dependency used by the bundler is not the good, it uses the one from the package.json 'browser' field instead of 'main'.

I need to do some futher research but I think I will simply remove the 'browser' field in the next release. At first, I added it to enable downloads from CDN but it is not required anymore.

**Comment by marozzocom** [comment] 2020-05-26 21:17
Interesting. The browser-field is new to me, no idea how it affects bundling and use with webpack. I'll be happy to try a new version in my current configuration and see whether it starts to work. But the issue is not acute, since in my case I don't absolutely need to bundle the package.

I could maybe also help contribute TS typings for the project, if you're interested in that.

**Comment by gmfmi** [comment] 2020-05-26 21:50
I just release a new v1.3.2 and it worked! I used parceljs but it should work exactly the same with Webpack. If you can give it a try using TypeScript, I would appreciate it :)

Thank you for your help on TypeScript but writing it purely in JS a choice. I previously worked with TS but I prefer to keep things simple for such a tiny library.

I am closing the issue.

**Closed as completed by gmfmi** 2020-05-26 21:50 UTC

**Comment by marozzocom** [comment] 2020-05-26 21:56
Just tested v1.3.2, works perfectly with TypeScript/Webpack now! Thank you!
